# Generated by Django 5.0.4 on 2024-05-21 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_email',
            field=models.BooleanField(default=False, verbose_name='статус подтверждения эл. почты'),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(unique=True, verbose_name='ключ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата генерации ключа')),
                ('expiration', models.DateTimeField(verbose_name='срок действия ключа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'проверка электронной почты',
            },
        ),
    ]
