# Generated by Django 5.0.4 on 2024-05-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='img_preview',
            field=models.ImageField(blank=True, null=True, upload_to='blog/posts/', verbose_name='превью (изображение)'),
        ),
    ]
