# Generated by Django 5.0.4 on 2024-04-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='manufactured_at',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='дата производства'),
        ),
    ]
