# Generated by Django 5.0.4 on 2024-04-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_manufactured_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='manufactured_at',
        ),
    ]
