# Generated by Django 5.0.4 on 2024-05-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.TextField(verbose_name='описание продукта'),
        ),
    ]
