# Generated by Django 5.0.4 on 2024-05-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_version_is_current_alter_version_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='признак текущей версии'),
        ),
    ]
